---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: NAMESPACE_PLACEHOLDER-git
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: NAMESPACE_PLACEHOLDER-git
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: NAMESPACE_PLACEHOLDER-git
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: NAMESPACE_PLACEHOLDER-git
spec:
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/YOUR_ORG/YOUR_REPO.git
      ref: refs/heads/GIT_BRANCH_PLACEHOLDER
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile.openshift
  output:
    to:
      kind: ImageStreamTag
      name: NAMESPACE_PLACEHOLDER-git:latest
  triggers:
    - type: ConfigChange
